version: '3.3'

services:
  php:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: donotshrthispwd
      MYSQL_DATABASE: shrdb
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: donotshrthispwd
